services:
  db:
    image: postgres:16.8
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=auctions
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  postgres_data:
  mongodata:
      